# This file was generated by the zone configuration script.
# It contains the defined rectangular zones for your parking system.

VIDEO_SOURCE_TOP = 0
FRAME_WIDTH = 1920
FRAME_HEIGHT = 1080

PARKING_ZONES = {
    'ZONE_1': (1340, 676, 1624, 810),
    'ZONE_10': (224, 671, 499, 803),
    'ZONE_2': (1335, 531, 1610, 664),
    'ZONE_3': (1325, 386, 1595, 519),
    'ZONE_4': (1077, 83, 1215, 321),
    'ZONE_5': (934, 78, 1067, 323),
    'ZONE_6': (797, 76, 922, 321),
    'ZONE_7': (658, 77, 774, 316),
    'ZONE_8': (258, 379, 527, 505),
    'ZONE_9': (235, 524, 509, 650),
}

ROAD_ZONES = {
    'ROAD_1': (995, 849, 1231, 1029),
    'ROAD_2': (994, 359, 1289, 845),
    'ROAD_3': (550, 358, 994, 537),
    'ROAD_4': (550, 538, 833, 832),
    'ROAD_5': (602, 835, 831, 1028),
}

ENTRYPOINT_ZONE = (1280, 852, 1642, 1016)

EXITPOINT_ZONE = (198, 842, 534, 989)

ENTRY_GATE_LIGHT = (1230, 845, 1248, 1023)

EXIT_GATE_LIGHT = (188, 825, 199, 993)

